---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: wordpress
    helm.sh/chart: {{ include "wordpress-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  ROOT_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  USER: {{ "wordpress" | b64enc | quote }}
  PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  DATABASE: {{ "wordpress" | b64enc | quote }}
