namespace: presslabs-system

resources:
  - ./crds/cert-manager.yaml
  - ./crds/mysql_mysqlbackup.yaml
  - ./crds/mysql_mysqlcluster.yaml
  - ./crds/wordpress.yaml
  - ./crds/prometheus.yaml


configurations:
- kustomizeconfig.yaml
