{{- if .Values.webhookSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "git-webhook.fullname" . }}
  labels:
    app: {{ template "git-webhook.name" . }}
    chart: {{ template "git-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  webhookSecret: {{ .Values.webhookSecret | b64enc | quote }}
{{- end }}
