{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "git-webhook.name" . }}
    chart: {{ template "git-webhook.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "git-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
