workspace:
  base: /go
  path: src/github.com/presslabs/stack

clone:
  docs:
    group: clone
    depth: 100
    tags: true
    image: plugins/git
    recursive: false

  site-clone:
    group: clone
    image: quay.io/presslabs/kluster-toolbox
    commands:
      - /usr/local/bin/setup-github-credentials.sh
      - git clone https://github.com/presslabs/presslabs.com /go/src/github.com/presslabs/stack/site
      - cd /go/src/github.com/presslabs/stack/site
      - git checkout prod
      - git pull origin prod
    secrets:
      - GH_PASSWORD
    environment:
      - GH_USER=presslabs-bot

  theme:
    group: clone
    image: quay.io/presslabs/kluster-toolbox
    commands:
      - /usr/local/bin/setup-github-credentials.sh
      - git clone https://github.com/presslabs/hugo-docs-theme /go/src/github.com/presslabs/stack/theme
      - mkdir -p /go/src/github.com/presslabs/stack/content /go/src/github.com/presslabs/stack/data /go/src/github.com/presslabs/stack/themes
      - cp -R /go/src/github.com/presslabs/stack/docs/* /go/src/github.com/presslabs/stack/content/
      - cd /go/src/github.com/presslabs/stack/theme
      - git checkout prod
      - git pull origin prod
      - mv /go/src/github.com/presslabs/stack/content/config.toml /go/src/github.com/presslabs/stack/
      - mv * /go/src/github.com/presslabs/stack/themes/
      - cp /go/src/github.com/presslabs/stack/themes/assets.json /go/src/github.com/presslabs/stack/data/
      - cp /go/src/github.com/presslabs/stack/themes/package.json /go/src/github.com/presslabs/stack/
    secrets:
      - GH_PASSWORD
    environment:
      - GH_USER=presslabs-bot

pipeline:
  build:
    image: desero/hugo:latest
    environment:
      - HUGO_ENV=production
    secrets: [ ALGOLIA_APP_ID, ALGOLIA_ADMIN_KEY, ALGOLIA_INDEX_NAME ]

  search:
    image: node:10.13.0
    secrets: [ ALGOLIA_APP_ID, ALGOLIA_ADMIN_KEY, ALGOLIA_INDEX_NAME, ALGOLIA_SEARCH_KEY, ALGOLIA_INDEX_FILE ]
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile
      - yarn algolia
      - rm -rf /go/src/github.com/presslabs/stack/site/wp-content/root/docs
      - mkdir /go/src/github.com/presslabs/stack/site/wp-content/root/docs
      - cp -a /go/src/github.com/presslabs/stack/public/* /go/src/github.com/presslabs/stack/site/wp-content/root/docs/
      - ls -la /go/src/github.com/presslabs/stack/site/wp-content/root/docs

  deploy:  # deploy to production
    image: appleboy/drone-git-push
    branch: prod
    commit: true
    commit.author.name: "Igor Debot"
    commit.author.email: "bot@presslabs.com"
    path: /drone/site
    commit_message: >
                    [docs] ${DRONE_COMMIT_MESSAGE}
    remote: https://github.com/presslabs/presslabs.com
    netrc.username: presslabs-bot
    secrets:
      - source: GH_TOKEN
        target: DRONE_NETRC_PASSWORD

  dependencies:
    pull: true
    image: quay.io/presslabs/bfc:latest
    environment:
      - GOPATH=/go/
    commands:
      - make dependencies

  lint:
    image: quay.io/presslabs/bfc:latest
    environment:
      - GOPATH=/go/
    commands:
      - helm repo add jetstack https://charts.jetstack.io
      - make lint
      - helm dep build charts/stack

  build-charts:
    image: quay.io/presslabs/kluster-toolbox
    commands:
      - make charts

  smoke-test:
    image: quay.io/presslabs/kluster-toolbox
    pull: true
    environment:
      - HELM_HOST=tiller:44134
    commands:
      - kubectl config set-cluster default --server=http://kubernetes:8080
      - kubectl config set-context default --cluster=default --namespace=default
      - kubectl config use-context default
      - dockerize -wait http://kubernetes:8080/healthz -skip-tls-verify -timeout 30s
      - helm version
      - helm install -n presslabs --namespace presslabs-sys ./charts/stack
      - helm install -n mysite ./charts/wordpress-site --set 'site.domains[0]=example.com'
      - helm ls

  git-webhook:
    image: quay.io/presslabs/bfc:latest
    environment:
      - GOPATH=/go/
    commands:
      - make -C git-webhook test

  publish-default-backend:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/default-backend
    dockerfile: Dockerfile.default-backend
    tags: [ "latest" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      branch: master
      event: push

  publish-default-backend:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/default-backend
    dockerfile: Dockerfile.default-backend
    tags: [ "${DRONE_TAG}" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: tag

  publish-git-webhook:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/git-webhook
    dockerfile: Dockerfile.git-webhook
    tags: [ "latest" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      branch: master
      event: push

  publish-git-webhook:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/git-webhook
    dockerfile: Dockerfile.git-webhook
    tags: [ "${DRONE_TAG}" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: tag

  publish-stack-chart:
    group: publish
    image: quay.io/presslabs/kluster-toolbox
    environment:
      - GH_USER=presslabs-bot
    commands:
      - cd charts
      - helm package stack
      - CHART="$(basename stack*.tgz)" ; MESSAGE="Publish $(basename $CHART .tgz)"
      - /usr/local/bin/gh put --skip-existing -m "$MESSAGE" "$CHART" "presslabs/charts/docs/"
    secrets:
      - GH_PASSWORD
    when:
      event: tag

  publish-wordpress-chart:
    group: publish
    image: quay.io/presslabs/kluster-toolbox
    environment:
      - GH_USER=presslabs-bot
    commands:
      - cd charts
      - helm package wordpress-site
      - CHART="$(basename wordpress-site*.tgz)" ; MESSAGE="Publish $(basename $CHART .tgz)"
      - /usr/local/bin/gh put --skip-existing -m "$MESSAGE" "$CHART" "presslabs/charts/docs/"
    secrets:
      - GH_PASSWORD
    when:
      event: tag

services:
  tiller:
    environment:
      - KUBERNETES_MASTER=http://kubernetes:8080
    image: gcr.io/kubernetes-helm/tiller:v2.11.0
  kubernetes:
    image: k8s.gcr.io/hyperkube:v1.10.7
    command:
      - kube-apiserver
      - --cert-dir=/tmp
      - --etcd-servers=http://etcd:2379
      - --insecure-port=8080
      - --insecure-bind-address=0.0.0.0
      - --secure-port=0
  etcd:
    image: quay.io/coreos/etcd:v3.3
    command:
      - etcd
      - --listen-peer-urls=http://localhost:0
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --advertise-client-urls=http://etcd:2379,http://etcd:4001
