workspace:
  base: /go
  path: src/github.com/presslabs/stack

pipeline:
  dependencies:
    pull: true
    image: quay.io/presslabs/bfc:latest
    environment:
      - GOPATH=/go/
    commands:
      - make dependencies

  lint:
    image: quay.io/presslabs/bfc:latest
    environment:
      - GOPATH=/go/
    commands:
      - helm repo add jetstack https://charts.jetstack.io
      - make lint
      - helm dep build charts/stack

  build-charts:
    image: quay.io/presslabs/kluster-toolbox
    commands:
      - make charts

  smoke-test:
    image: quay.io/presslabs/kluster-toolbox
    pull: true
    environment:
      - HELM_HOST=tiller:44134
    commands:
      - kubectl config set-cluster default --server=http://kubernetes:8080
      - kubectl config set-context default --cluster=default --namespace=default
      - kubectl config use-context default
      - dockerize -wait http://kubernetes:8080/healthz -skip-tls-verify -timeout 30s
      - helm version
      - helm install -n presslabs --namespace presslabs-sys ./charts/stack
      - helm install -n mysite ./charts/wordpress-site --set 'site.domains[0]=example.com'
      - helm ls

  git-webhook:
    image: quay.io/presslabs/bfc:latest
    environment:
      - GOPATH=/go/
    commands:
      - make -C git-webhook test

  publish-default-backend-branch:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/default-backend
    dockerfile: Dockerfile.default-backend
    tags: [ "latest" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      branch: master
      event: push

  publish-default-backend-tag:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/default-backend
    dockerfile: Dockerfile.default-backend
    tags: [ "${DRONE_TAG}" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: tag

  publish-git-webhook:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/git-webhook
    dockerfile: Dockerfile.git-webhook
    tags: [ "latest" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      branch: master
      event: push

  publish-git-webhook:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/git-webhook
    dockerfile: Dockerfile.git-webhook
    tags: [ "${DRONE_TAG}" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: tag

  publish-stack-chart:
    group: publish
    image: quay.io/presslabs/kluster-toolbox
    environment:
      - GH_USER=presslabs-bot
    commands:
      - cd charts
      - helm package stack
      - CHART="$(basename stack*.tgz)" ; MESSAGE="Publish $(basename $CHART .tgz)"
      - /usr/local/bin/gh put --skip-existing -m "$MESSAGE" "$CHART" "presslabs/charts/docs/"
    secrets:
      - GH_PASSWORD
    when:
      event: tag

  publish-wordpress-chart:
    group: publish
    image: quay.io/presslabs/kluster-toolbox
    environment:
      - GH_USER=presslabs-bot
    commands:
      - cd charts
      - helm package wordpress-site
      - CHART="$(basename wordpress-site*.tgz)" ; MESSAGE="Publish $(basename $CHART .tgz)"
      - /usr/local/bin/gh put --skip-existing -m "$MESSAGE" "$CHART" "presslabs/charts/docs/"
    secrets:
      - GH_PASSWORD
    when:
      event: tag

services:
  tiller:
    environment:
      - KUBERNETES_MASTER=http://kubernetes:8080
    image: gcr.io/kubernetes-helm/tiller:v2.11.0
  kubernetes:
    image: k8s.gcr.io/hyperkube:v1.10.7
    command:
      - kube-apiserver
      - --cert-dir=/tmp
      - --etcd-servers=http://etcd:2379
      - --insecure-port=8080
      - --insecure-bind-address=0.0.0.0
      - --secure-port=0
  etcd:
    image: quay.io/coreos/etcd:v3.3
    command:
      - etcd
      - --listen-peer-urls=http://localhost:0
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --advertise-client-urls=http://etcd:2379,http://etcd:4001

  trigger-docs-build:
    image: plugins/downstream
    server: https://drone.presslabs.net
    secrets: [ DRONE_TOKEN ]
    repositories:
      - presslabs/docs
    when:
      branch: master
      event: push
