apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-site.fullname" . }}-memcached
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/component: cache
    helm.sh/chart: {{ include "wordpress-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: 11211
    name: memcached
  clusterIP: None
  selector:
    app.kubernetes.io/component: cache
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: memcached
    app.kubernetes.io/part-of: wordpress

