---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-site.fullname" . }}
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/part-of: wordpress
    helm.sh/chart: {{ include "wordpress-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if and .Values.code .Values.code.git }}
  id_rsa: {{ .Values.code.git.ssh_private_key | b64enc | quote }}
  {{- end }}

  {{- if and .Values.media .Values.media.gcs }}
  google_application_credentials.json: {{ required "A valid media.gcs.google_credentials entry required!" .Values.media.gcs.google_credentials | b64enc | quote}}
  {{- end }}
