apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ template "stack.fullname" . }}-default
  labels:
    app: {{ include "stack.name" . }}
    chart: {{ include "stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.letsencrypt.enabled }}
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ required "A valid .letsencrypt.email is required." .Values.letsencrypt.email }}
    server: {{ .Values.letsencrypt.server }}
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: {{ template "stack.fullname" . }}-letsencrypt
    # Enable the HTTP01 challenge mechanism for this Issuer
    http01: {}
{{ else }}
  ca:
    secretName: {{ template "stack.fullname" . }}-ca
{{- end }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "stack.fullname" . }}-ingress-default
  labels:
    app: {{ include "stack.name" . }}
    chart: {{ include "stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ template "stack.fullname" . }}-ingress-default
  commonName: "ingress.local"
  issuerRef:
    name: {{ template "stack.fullname" . }}-default
    kind: ClusterIssuer

{{- if not .Values.letsencrypt.enabled }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ template "stack.fullname" . }}-ca-issuer
  labels:
    app: {{ include "stack.name" . }}
    chart: {{ include "stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "stack.fullname" . }}-ca
  labels:
    app: {{ include "stack.name" . }}
    chart: {{ include "stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ template "stack.fullname" . }}-ca
  commonName: "Presslabs Stack - Root CA ({{ .Release.Name }})"
  organization:
  - Presslabs Stack
  dnsNames:
    - stack.presslabs.org
  duration: "87600h"
  isCA: true
  issuerRef:
    name: {{ template "stack.fullname" . }}-ca-issuer
    kind: Issuer
{{- end }}
