apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wordpress-site.fullname" . }}-memcached
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/component: cache
    helm.sh/chart: {{ include "wordpress-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.memcached.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: cache
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: memcached
      app.kubernetes.io/part-of: wordpress
  serviceName: {{ include "wordpress-site.fullname" . }}-memcached
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cache
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: memcached
        app.kubernetes.io/part-of: wordpress
    spec:
      containers:
      - name: memcached
        command:
          - memcached
        args:
          - "-m"
          - "128"
        image: docker.io/library/memcached:1.5.12
        ports:
        - containerPort: 11211
          name: memcached
      - name: memcached-exporter
        image: quay.io/prometheus/memcached-exporter:v0.5.0
        ports:
        - containerPort: 9150
          name: prometheus
