baseURL = "https://www.presslabs.com/docs/stack"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true
theme = "hugo-docs-theme"
languageCode = "en-us"
title = "Presslabs Stack DOCS"

[markup]
  defaultMarkdownHandler = "goldmark"

[params]
  related = true
  logo_text = "DOCS"
  versions = false

[params.algolia]
  appId = "0TS6NFHDBC"
  apiKey = "b2efcfd6516eed7a2f19269f9cb13acb"
  indexName = "Stack Docs"
  vars = ["title", "description", "content", "date", "lastmod", "permalink", "text", "lvl0", "lvl1", "url"]

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "menu.global.parent"
  weight = 150

[[menu.global]]
  name = "About Stack"
  url = "/about-stack"
  weight = 1

[[menu.global]]
  name = "Quickstart"
  identifier = "quickstart"
  weight = 2

[[menu.global]]
  name = "How-to guides"
  identifier = "how-to"
  weight = 3

[[menu.global]]
  name = "Development"
  identifier = "development"
  parent = "how-to"
  weight = 1

[[menu.global]]
  name = "Concepts"
  identifier = "concepts"
  weight = 4

[[menu.global]]
  name = "References"
  identifier = "references"
  weight = 5

[[menu.global]]
  name = "Contributing"
  url = "/contributing"
  weight = 6
